lsc -c wallet/add-coin.ls
lsc -c wallet/address-link.ls
lsc -c wallet/api.ls
lsc -c wallet/apply-transactions.ls
lsc -c wallet/autodetect-lang.ls
lsc -c wallet/browser/history.ls
lsc -c wallet/browser/location.ls
lsc -c wallet/browser/window.ls
lsc -c wallet/calc-amount.ls
lsc -c wallet/calc-wallet.ls
lsc -c wallet/close.ls
lsc -c wallet/copied-inform.ls
lsc -c wallet/data-scheme.ls
lsc -c wallet/deadline.ls
lsc -c wallet/fake.ls
lsc -c wallet/get-device.ls
lsc -c wallet/get-lang.ls
lsc -c wallet/get-name-mask.ls
lsc -c wallet/get-primary-coin.ls
lsc -c wallet/get-primary-info.ls
lsc -c wallet/get-record.ls
lsc -c wallet/guid.ls
lsc -c wallet/hex-util.ls
#lsc -c wallet/history-funcs.ls
lsc -c wallet/install-plugin.ls
lsc -c wallet/invoice-funcs.ls
lsc -c wallet/json-parse.ls
lsc -c wallet/langs/en.ls
lsc -c wallet/langs/ru.ls
lsc -c wallet/langs/ua.ls
lsc -c wallet/load-rates.ls
lsc -c wallet/load-registry.ls
lsc -c wallet/main.ls
lsc -c wallet/main2.ls
lsc -c wallet/math.ls
lsc -c wallet/menu-funcs.ls
lsc -c wallet/mirror.ls
#lsc -c wallet/modal.ls
lsc -c wallet/navigate.ls
lsc -c wallet/new-account.ls
lsc -c wallet/newseed-funcs.ls
lsc -c wallet/oldseed.ls
lsc -c wallet/pending-tx.ls
lsc -c wallet/pin.ls
lsc -c wallet/plugin-loader.ls
lsc -c wallet/providers.ls
lsc -c wallet/proxy.ls
lsc -c wallet/refresh-account.ls
lsc -c wallet/refresh-wallet.ls
lsc -c wallet/resolve-address.ls
#lsc -c wallet/rest/button.ls
#lsc -c wallet/rest/cap.ls
#lsc -c wallet/rest/Container.ls
#lsc -c wallet/rest/contract-create.ls
#lsc -c wallet/rest/contract-render.ls
#lsc -c wallet/rest/date.ls
#lsc -c wallet/rest/input.ls
#lsc -c wallet/rest/label.ls
#lsc -c wallet/rest/number.ls
#lsc -c wallet/rest/select.ls
#lsc -c wallet/rest/textarea.ls
lsc -c wallet/round.ls
lsc -c wallet/round5.ls
lsc -c wallet/round5edit.ls
lsc -c wallet/scroll-top.ls
lsc -c wallet/seed.ls
lsc -c wallet/send-form.ls
lsc -c wallet/send-funcs.ls
lsc -c wallet/set-page-theme.ls
lsc -c wallet/themes.ls
lsc -c wallet/tools.ls
lsc -c wallet/topup-loader.ls
lsc -c wallet/topup.ls
lsc -c wallet/transactions.ls
lsc -c wallet/use-network.ls
lsc -c wallet/wallet-funcs.ls
lsc -c wallet/wallets-funcs.ls
lsc -c wallet/web3.ls
lsc -c wallet/whois.ls
lsc -c wallet/words-to-utf8.ls
lsc -c wallet/workflow.ls