// Generated by LiveScript 1.5.0
(function () {
  var ref$, get, post;
  (ref$ = require('superagent')), (get = ref$.get), (post = ref$.post);
  module.exports = function (store) {
    return get('https://web3.space/user-lang').end(function (err, res) {
      if (err != null) {
        return;
      }
      if (res.text === 'ua') {
        return (store.lang = 'ua');
      }
      if (res.text === 'ru') {
        return (store.lang = 'ru');
      }
    });
  };
}.call(this));
