// Generated by LiveScript 1.5.0
(function(){
  module.exports = function(){
    var ref$, m, r;
    if ((typeof document != 'undefined' && document !== null ? (ref$ = document.documentElement) != null ? ref$.clientWidth : void 8 : void 8) == null) {
      return 'mobile';
    }
    m = Math.max(document.documentElement.clientWidth, window.innerWidth || 0);
    return r = (function(){
      switch (false) {
      case !(m > 800):
        return 'desktop';
      default:
        return 'mobile';
      }
    }());
  };
}).call(this);
