// Generated by LiveScript 1.5.0
(function(){
  module.exports = function(store){
    var ref$;
    return (ref$ = store.langs[store.lang]) != null
      ? ref$
      : store.langs.en;
  };
}).call(this);
