// Generated by LiveScript 1.5.0
(function(){
  var wallets, history, send, receive, locked, newseed, sent, loading, invoice, terms, out$ = typeof exports != 'undefined' && exports || this;
  wallets = require('./pages/wallets.js');
  history = require('./pages/history.js');
  send = require('./pages/send.js');
  receive = require('./pages/receive.js');
  locked = require('./pages/locked.js');
  newseed = require('./pages/newseed.js');
  sent = require('./pages/sent.js');
  loading = require('./pages/loading.js');
  invoice = require('./pages/invoice.js');
  terms = require('./pages/terms.js');
  out$.loading = loading;
  out$.wallets = wallets;
  out$.history = history;
  out$.send = send;
  out$.receive = receive;
  out$.locked = locked;
  out$.newseed = newseed;
  out$.sent = sent;
  out$.invoice = invoice;
  out$.terms = terms;
}).call(this);
