// Generated by LiveScript 1.6.0
(function(){
	var ref$, filter, sortBy, reverse, getInstallList, common, getCoins, out$ = typeof exports != 'undefined' && exports || this;
	ref$ = require('prelude-ls'), filter = ref$.filter, sortBy = ref$.sortBy, reverse = ref$.reverse;
	getInstallList = require('./install-plugin.js').getInstallList;
	common = function(store){
		var vlx2, btc, native, eth, vlx_evm, coins;
		vlx2 = require('../web3t/plugins/vlx2-coin.js');
		btc = require('../web3t/plugins/btc-coin.js');
		native = require('../web3t/plugins/sol-coin.js');
		eth = require('../web3t/plugins/eth-coin.js');
		vlx_evm = require('../web3t/plugins/vlx-coin.js');
		coins = [native, vlx_evm, vlx2, btc, eth];
		return coins;
	};
	out$.getCoins = getCoins = function(store, cb){
		var network, base;
		network = store.current.network;
		base = filter(function(it){
			var ref$;
			return it[network] != null && it.type === 'coin' && it.enabled === true && !(((ref$ = it[network]) != null ? ref$.disabled : void 8) === true);
		})(
				filter(function(it){
					return it != null;
				})(
						common(store)));
		return getInstallList(function(err, items){
			var installed, all;
			if (err != null) {
				return cb(err);
			}
			installed = filter(function(it){
				return it.enabled !== false;
			})(
					filter(function(it){
						return it.type === 'coin';
					})(
							items));
			all = reverse(base.concat(installed));
			return cb(null, all);
		});
	};
}).call(this);
