// Generated by LiveScript 1.6.0
(function(){
  var filter, getInstallList, common, reverse, getCoins, out$ = typeof exports != 'undefined' && exports || this;
  filter = require('prelude-ls').filter; reverse = require('prelude-ls').reverse;
  getInstallList = require('./install-plugin.js').getInstallList;
  common = function(store){
	var vlx2, btc, native, coins;
	vlx2 = require('../web3t/plugins/vlx2-coin.js');
	btc = require('../web3t/plugins/btc-coin.js');
	native = require('../web3t/plugins/sol-coin.js');
	coins = [vlx2, native, btc];
	return coins;
  };
  out$.getCoins = getCoins = function(store, cb){
	var network, base;
	network = store.current.network;
	base = filter(function(it){
	  return !it[network].disabled === true;
	})(
		filter(function(it){
		  return it.enabled;
		})(
			filter(function(it){
			  return it.type === 'coin';
			})(
				filter(function(it){
				  return it != null;
				})(
					common(store)))));
	return getInstallList(function(err, items){
	  var installed, all;
	  if (err != null) {
		return cb(err);
	  }
	  installed = filter(function(it){
		return it.enabled !== false;
	  })(
		  filter(function(it){
			return it.type === 'coin';
		  })(
			  items));
	  all = reverse(base.concat(installed));
	  return cb(null, all);
	});
  };
}).call(this);
