// Generated by LiveScript 1.6.0
(function(){
  var filter, getInstallList, window, queryRelated, common, getCoins, out$ = typeof exports != 'undefined' && exports || this;
  filter = require('prelude-ls').filter;
  getInstallList = require('./install-plugin.js').getInstallList;
  window = require('./browser/window.js');
  queryRelated = function(token, coin){
    if (window.location.search.indexOf("plugin=" + token) > -1) {
      return coin;
    }
  };
  common = [
    require('../web3t/plugins/vlx2-coin.js'),
    require('../web3t/plugins/btc-coin.js'), require('../web3t/plugins/eth-coin.js'), require('../web3t/plugins/usdt-coin.js'), require('../web3t/plugins/ltc-coin.js')];
  out$.getCoins = getCoins = function(cb){
    var base;
    base = filter(function(it){
      return it.enabled;
    })(
    filter(function(it){
      return it.type === 'coin';
    })(
    filter(function(it){
      return it != null;
    })(
    common)));
    return getInstallList(function(err, items){
      var installed, all;
      if (err != null) {
        return cb(err);
      }
      installed = filter(function(it){
        return it.type === 'coin';
      })(
      items);

      // HACK: it got reversed later by reverse concatenation at recursion

      all = base.concat(installed).reverse();
      return cb(null, all);
    });
  };
}).call(this);
