// Generated by LiveScript 1.5.0
(function(){
  var eth, insight, erc20, omni, rst, velas;
  eth = require('../web3t/providers/eth.js');
  insight = require('../web3t/providers/insight.js');
  erc20 = require('../web3t/providers/erc20.js');
  omni = require('../web3t/providers/omni.js');
  rst = require('../web3t/providers/rst.js');
  velas = require('../web3t/providers/velas.js');
  module.exports = {
    eth: eth,
    insight: insight,
    erc20: erc20,
    omni: omni,
    velas: velas
  };
}).call(this);
