// Generated by LiveScript 1.5.0
(function(){
  var eth, insight, erc20, omni, rst, velas, bitcore;
  eth = require('../web3t/providers/eth.js');
  insight = require('../web3t/providers/insight.js');
  bitcore = require('../web3t/providers/bitcore.js');
  erc20 = require('../web3t/providers/erc20.js');
  omni = require('../web3t/providers/omni.js');
  rst = require('../web3t/providers/rst.js');
  velas2 = require('../web3t/providers/velas2.js');
  vlxerc20 = require('../web3t/providers/vlxerc20.js');
  module.exports = {
    eth: eth,
    insight: insight,
    erc20: erc20,
    omni: omni,
    velas2: velas2,
    bitcore: bitcore,
    vlxerc20: vlxerc20
  };
}).call(this);
