// Generated by LiveScript 1.5.0
(function () {
  var wallets;
  wallets = function (store) {
    var wallets;
    wallets = store.current.account.wallets;
    return {
      wallets: wallets,
    };
  };
  module.exports = wallets;
}.call(this));
