// Generated by LiveScript 1.5.0
(function(){
  var react, getPrimaryInfo, getLang, confirmationModal, state, confirm, prompt, toString$ = {}.toString, out$ = typeof exports != 'undefined' && exports || this;
  out$.confirm = confirm = function(store, text, cb){
    store.current.confirmation = text;
    return store.current.confirmationCallback = (result) => {
      store.current.confirmation = false;
      store.current.confirmationCallback = null;
      cb(result);
    };
  };
	out$.confirm2 = function(store, component, cb){
		store.current.confirmationComponent = component;
		return store.current.confirmationCallback = (result) => {
			store.current.confirmationComponent = false;
			store.current.confirmationCallback = null;
			cb(result);
		};
	};
  out$.prompt = prompt = function(store, text, cb){
    store.current.prompt = text;
    return store.current.confirmationCallback = (result) => {
      store.current.confirmation = false;
      store.current.confirmationCallback = null;
      cb(result);
    };
  };
	out$.modal = modal = function(store, cb){
		store.current.currentNetworkDetails.show = true;
		return store.current.bridgeInfoCallback = (res) => {
			store.current.currentNetworkDetails.show = false;
			store.current.bridgeInfoCallback = null;
			cb(null);		
		};
	};
}).call(this);
