// Generated by LiveScript 1.5.0
(function(){
  var react, getPrimaryInfo, getLang, confirmationModal, state, confirm, prompt, toString$ = {}.toString, out$ = typeof exports != 'undefined' && exports || this;
  out$.confirm = confirm = function(store, text, cb){
    store.current.confirmation = text;
    return store.current.confirmationCallback = (result) => {
      store.current.confirmation = false;
      store.current.confirmationCallback = null;
      cb(result);
    };
  };
  out$.prompt = prompt = function(store, text, cb){
    store.current.prompt = text;
    return store.current.confirmationCallback = (result) => {
      store.current.confirmation = false;
      store.current.confirmationCallback = null;
      cb(result);
    };
  };
}).call(this);
