// Generated by LiveScript 1.5.0
(function () {
  var location, document, scrollTo, mockWindow, ref$;
  location = require('./location.js');
  document = {};
  scrollTo = function () {};
  mockWindow = {
    scrollTo: scrollTo,
    location: location,
    document: document,
  };
  module.exports =
    typeof window != 'undefined' && window !== null ? window : mockWindow;
  module.exports.scrollTo =
    (ref$ = module.exports.scrollTo) != null ? ref$ : scrollTo;
}.call(this));
