name: e2e-tests
on:
  pull_request:
concurrency:
  group: wallet-tests-ios-${{github.event.pull_request.number}}
  cancel-in-progress: true
jobs:
  ios-tests:
    runs-on: macos-internal2
    steps:
      - name: fix up git URLs
        run: echo -e '[url "https://github.com/"]\n  insteadOf = "git@github.com:"' >> ~/.gitconfig

      - name: fix git URLs
        run: git config --global url."https://github.com/".insteadOf git://github.com/ --replace-all

      - uses: actions/checkout@v2

      - name: create sentry props
        run: printf "defaults.url=https://sentry.io/\ndefaults.org=velas-6g\ndefaults.project=wallet\nauth.token=${{secrets.SENTRY_AUTH_TOKEN}}" > sentry.properties && cp sentry.properties ios/sentry.properties && cp sentry.properties android/sentry.properties

      - name: yarn install
        run: yarn install

      - name: pod install
        run: yarn pod || pod install --repo-update

      - name: build ios app
        run: npx detox build -c ios

      - name: run e2e tests ios
        run: REPORT_DIR=ios-test-report npx detox test -c ios

      - name: upload artifacts
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: ios-test-report
          path: |
            ios-test-report
            artifacts/

  android-tests:
    runs-on: macos-internal2
    steps:
      - name: fix up git URLs
        run: echo -e '[url "https://github.com/"]\n  insteadOf = "git@github.com:"' >> ~/.gitconfig

      - name: fix git URLs
        run: git config --global url."https://github.com/".insteadOf git://github.com/ --replace-all

      - uses: actions/checkout@v2

      - name: create sentry props
        run: printf "defaults.url=https://sentry.io/\ndefaults.org=velas-6g\ndefaults.project=wallet\nauth.token=${{secrets.SENTRY_AUTH_TOKEN}}" > sentry.properties && cp sentry.properties ios/sentry.properties && cp sentry.properties android/sentry.properties

      - name: yarn install
        run: yarn install

      - name: build android app
        run: npx detox build -c android || npx detox build -c android || npx detox build -c android || (exit 13 && echo " - - - - - Failed to build android app - - - - -")

      - name: run e2e tests android
        run: REPORT_DIR=android-test-report npx detox test -c android

      - name: upload artifacts
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: android-test-report
          path: |
            android-test-report
            artifacts/
