name: tests
on:
  pull_request:
concurrency:
  group: mobile-wallet-tests-${{github.event.pull_request.number}}
  cancel-in-progress: true
jobs:
  check-dev-domain-presence:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2

      - name: check dev domain absence in repository code
        run: |
          grep -Ri ${{secrets.SECRET_DOMAIN}} . \
          --exclude-dir node_modules \
          --exclude-dir e2e/node_modules \
          --exclude-dir .git || exit 0 && \
          echo ' - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -' && \
          echo 'The development domain was found in repository code.' && \
          echo 'See filename(s) above.' && \
          echo 'Domain is replaced with *** due to security.' && \
          echo ' - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -' && \
          exit 13
